### ISSUE TITLE
That Normal??

### ISSUE THREAD

**Issue by Secretov** [ChalkyBrush/roshpit-bug-tracker#407] opened 2018-03-07 18:14 UTC
just look at item (required lvl) https://www.roshpit.ca/market/auction/240856

**Comment by redledcat** [comment] 2018-03-07 23:06
yes, that legacy, not a bug. there are a lot of 120 lv copies and some 134 lv, 114lv etc.
close the issue

**Closed as completed** 2018-03-08 19:54 UTC
