### ISSUE TITLE
Flamewaker

### ISSUE THREAD

**Issue by calltobat9** [ChalkyBrush/roshpit-bug-tracker#933] opened 2018-12-28 13:18 UTC
(Arcana W) - Since the damage type was changed to physical, I suggest changing the rune W1(Brimstone) to post-mitigation damage 1-level-0,7%

**Comment by redledcat** [comment] 2018-12-28 15:02
why

**Comment by calltobat9** [comment] 2018-12-28 16:21
> why

it makes no sense now to wear a "Fire Deity Crown" as there is magical damage in it, no matter how hard you build this hero, there are those who are dozens of times stronger than him, this is very personal

**Comment by calltobat9** [comment] 2018-12-28 16:29
> why

ArcaneQ1 the most useless skill (it would also change)

**Comment by Nintai** [comment] 2018-12-28 16:37
In my opinion W Arcana can work really good without any post mitigation dmg increase, the reason for that is the 0.1s dmg tick rate, which will destroy any steadfast mobs as long as u have the dmg. Fire Deity Crown is still pretty good since it multiplies the previous W dmg u would have done (meaning  by 2.5x and also stuns enemies for ur W1 to work.

Also i should note that this is a bug tracker and not a suggestion tracker 😉 
For suggestions we mainly use the discord

**Comment by calltobat9** [comment] 2018-12-28 16:50
> In my opinion W Arcana can work really good without any post mitigation dmg increase, the reason for that is the 0.1s dmg tick rate, which will destroy any steadfast mobs as long as u have the dmg. Fire Deity Crown is still pretty good since it multiplies the previous W dmg u would have done (meaning by 2.5x and also stuns enemies for ur W1 to work.
> 
> Also i should note that this is a bug tracker and not a suggestion tracker 😉
> For suggestions we mainly use the discord

compare the damage of Mountain Protector and Flamewaker, it is not even close! Let alone the hero's maneuverability (but the developer will decide this)

**Comment by DeckardCainRPC** [comment] 2018-12-30 08:47
i would like to state, for the record, that the STR Flamewaker glove arcana build is definitely, DEFINITELY capable of the highest burst AND sustained damage output of anything in RPC at time of writing. it can easily oneshot Shadow of Bahamut, even without optimized gear - another developer demonstrated this, and i confirmed it myself.

any user who is caught suggesting that the arcana needs buffs is either a master clown, or a brainlet, and should be laughed at either way

**Comment by calltobat9** [comment] 2018-12-30 11:03
> i would like to state, for the record, that the STR Flamewaker glove arcana build is definitely, DEFINITELY capable of the highest burst AND sustained damage output of anything in RPC at time of writing. it can easily oneshot Shadow of Bahamut, even without optimized gear - another developer demonstrated this, and i confirmed it myself.
> 
> any user who is caught suggesting that the arcana needs buffs is either a master clown, or a brainlet, and should be laughed at either way

Throw me a link to the build where you kill Shadow of Bahamut with one hit and so that this build has arcanaW

**Comment by DeckardCainRPC** [comment] 2018-12-31 18:48
@calltobat9 this will be the last time you doubt Deckard Cain

https://www.youtube.com/watch?v=UD5E1NFtVaw&feature=youtu.be

for your impertinence, i will laugh at every bug report you ever submit, especially if it pertains to game balance

**Comment by calltobat9** [comment] 2019-01-01 08:36
> @calltobat9 this will be the last time you doubt Deckard Cain
> 
> https://www.youtube.com/watch?v=UD5E1NFtVaw&feature=youtu.be
> 
> for your impertinence, i will laugh at every bug report you ever submit, especially if it pertains to game balance

well was wrong, sorry!

**Comment by redledcat** [comment] 2019-04-07 15:31
ok I'm closing it because wtf

**Closed as completed by redledcat** 2019-04-07 15:31 UTC
