### ISSUE TITLE
[4.0] Umbra watched Scarloth drop a pair of Spellfire Gloves which are equipped to the Feet slot, and now all hell has broken loose

### ISSUE THREAD

**Issue by DeckardCainRPC** [ChalkyBrush/roshpit-bug-tracker#1406] opened 2020-02-03 03:58 UTC
he curated it. the absolute madman curated it. so now, Spellfire Gloves, NO BULLSHIT, has an entry on the fucking Feet page https://www.roshpit.ca/items?slot=feet , and it claims to be equipped to Slot: Feet, and Spellfire Gloves no longer has an entry on the fucking Gloves page. i wish i were kidding, look for yourself: https://www.roshpit.ca/items?slot=hands

and yes, because i'm sure you're wondering, he can equip those Spellfire Gloves to his heroes, and they function normally.

**Comment by Nintai** [comment] 2020-02-03 05:11
Yeah, this was my fuckup, and thank god it was only "Spellfire Boots" that are affected. Should be an easy fix 😛

**Comment by ChalkyBrush** [comment] 2020-02-03 15:05
well the game is fixed now, any website issues caused by this please make a new bug post

**Closed as completed by ChalkyBrush** 2020-02-03 15:05 UTC
