### ISSUE TITLE
Solunia head arcana Q2

### ISSUE THREAD

**Issue by StillStealSteel** [ChalkyBrush/roshpit-bug-tracker#274] opened 2018-01-09 18:15 UTC
The description for Q2 mentions something about "percentage of current health added to base ability damage". And lower we have something like "HEALTH ADDED TO BASE ABILITY DAMAGE: 1000%".
How someone should understand anything from this description? I if have 1m hp i will add 10m to base ability or what? Or is it percentage of ... of ... WHAT? or it's just add 1000% of base ability or it's 1000% of PERCENTAGES OF CURRENT HEALTH so if you right now have 50% hp you will boost base ability by 500%? Maybe it's language barrier and i don't understand this description right, but WTF is this shit?
And this complication (about % of current health) is so bad because with Q1 you have 2 stages: you dead or you HAVE FULL fucnk hp.

Besided this retarded description i haven't found anything about this `+ to base ability` in the source code and the table when you point the cursor on hero stats doesn't show any addictive base ability besides other sources of base ability. 
Thats why this helmet does like 0 damage even if you have like 25m base attack (not even mentioning green) damage and 5m hp.

**Comment by bavibi** [comment] 2018-01-14 03:40
It's flat number

        if not ignore_effects and attacker:HasModifier("modifier_solunia_arcana1") then
            local b_a_level = Runes:GetTotalRuneLevelGeneric(attacker, 2, 0)
            if b_a_level > 0 then
                damage = damage + attacker:GetHealth() * 0.1 * b_a_level

**Comment by redledcat** [comment] 2018-11-20 19:28
uhh, close it. not a bug, just bad description.

**Closed as completed** 2018-11-20 19:34 UTC
Labels: enhancement, bug: math or logic
