### ISSUE TITLE
Divine Purity checks target's Armor before dealing Pure Holy damage

### ISSUE THREAD

**Issue by DeckardCainRPC** [ChalkyBrush/roshpit-bug-tracker#1282] opened 2019-10-15 17:52 UTC
according to NoticeMeSenpai, Divine Purity's damage instance is first reduced by the enemy's physical resistance from Armor, before it's converted to Pure Holy damage.

he says we had a conversation "weeks ago" about seinaru's boot arcana, and i only vaguely recall the details of that discussion, but he swears i "confirmed" that Divine Purity was misbehaving like this, and that he tested it himself and provided me screenshots of the target dummy to prove it. i have no recollection of that whatsoever, and if i did, i would have filed this bug report sooner, and made it very clear to him that the behavior he observed was a gigantic fucking bug.

whenever someone checks this, and if they determine that Divine Purity IS in fact being mitigated by Armor as he claims, PLEASE remember to check the new and improved Proud Gloves for the same bug.

**Comment by Nintai** [comment] 2019-10-15 17:56
Its not a bug, its a feature to allow negative armor to increase said damage 😛 

Please discuss this, while i plan my escape

**Comment by ChalkyBrush** [comment] 2019-10-15 17:59
fixed in 4.0 LULw

**Comment by ChalkyBrush** [comment] 2019-10-15 17:59
but actually, in 4.0 this is 100% fixd

**Comment by DeckardCainRPC** [comment] 2019-10-15 18:27
okay now i suspect that NOBODY knows what the fuck is going on, because he sent me this:

[1:51 PM]
FeedingOversight:
	HAHHAHA
	aight seems like it got fixed
	back then it only show dmg number followed up with Pure without any element

**Closed as completed** 2020-01-10 16:40 UTC
