### ISSUE TITLE
Chernobog boots arcana doesn't work with wind deity crown.

### ISSUE THREAD

**Issue by SSRandyTolentino** [ChalkyBrush/roshpit-bug-tracker#429] opened 2018-03-14 23:15 UTC
Chernobog's demon flight and shadow stalk don't proc Wind Deity Crown.

**Comment by ChalkyBrush** [comment] 2018-03-14 23:41
because it has no way of dealing damage (not a bug). The right click effect is auto attacks and so benefits from a host of On Attack Landed effects

**Closed as completed by ChalkyBrush** 2018-03-14 23:41 UTC
