### ISSUE TITLE
[Elemental Warlord] Helm arcana q1 and q3 runes count are confused

### ISSUE THREAD

**Issue by TheVietboi** [ChalkyBrush/roshpit-bug-tracker#1283] opened 2019-10-16 14:31 UTC
Left Click Last Monday at 7:55 PM
dragonborne helm (elemental warlord) uses q3's rune level instead of q1 to calculate the post mit

And he did not bullshit
![image](https://user-images.githubusercontent.com/51455274/66928936-5da0fd80-f05c-11e9-9b4b-85f56bcda45d.png)

**Comment by Nintai** [comment] 2019-10-16 14:32
Not a bug, its a feature

**Comment by GoToNightmare** [comment] 2019-10-16 15:26
fixed in /pull/675

**Closed as completed by GoToNightmare** 2019-10-16 15:26 UTC
