### ISSUE TITLE
[4.0] Some mobs push Djanghor till the edge of the map

### ISSUE THREAD

**Issue by harveystays** [ChalkyBrush/roshpit-bug-tracker#1398] opened 2020-01-27 14:34 UTC
When Djanghor in yearbeast form is pushed by some mobs, it goes way too far and get stuck.
Especially end of right side of Sea fortress, those golems throw stone to push heroes pushe djangor till the edge of the map so I must use town portal to get out from there.

![image](https://user-images.githubusercontent.com/60297159/73182985-6033e880-415d-11ea-950c-9de2a4599d0f.png)

see minimap how far i've went. i never used shortcut or skipping sth.

**Comment by crazybrain228** [comment] 2020-01-28 11:24
Duplicate of #1347

**Closed as completed** 2020-04-27 07:49 UTC
