### ISSUE TITLE
Redfall lina not triggered

### ISSUE THREAD

**Issue by ablyx** [ChalkyBrush/roshpit-bug-tracker#174] opened 2017-11-28 16:33 UTC
![20171129002634_1](https://user-images.githubusercontent.com/16754650/33331463-9f7df83a-d49c-11e7-92fc-74bc4b555d51.jpg)
(ignore the pause, was trying to figure out which button screenshots)

No skips were done, ta was not invis when he approached lina.

**Comment by redledcat** [comment] 2017-11-28 17:18
Here is the video of reproduction (1:02)
https://youtu.be/oYUJc7CpP0o

**Comment by redledcat** [comment] 2017-11-28 17:18
#79

**Comment by ChalkyBrush** [comment] 2017-11-29 00:47
should be fixed in next patch

**Comment by redledcat** [comment] 2018-01-10 19:26
people keeps reporting Lina still bugs somehow.
Trapper involved 100% sure

**Comment by redledcat** [comment] 2018-01-20 14:19
@ChalkyBrush It's not caused by Vanish.
Think it's BKB state from Hope or invis from ultimate cause this

**Comment by redledcat** [comment] 2018-01-20 14:22
Tested R invis and it seems to be ok too.
Hope of Saitaru?

**Comment by redledcat** [comment] 2019-05-18 21:07
Should be fixed by Nintai next patch (decoy was flagged as hero unit)

**Closed as completed by redledcat** 2019-05-18 21:07 UTC
