### ISSUE TITLE
[Djanghor] Using his E during wolf form cap both max and min movespeed at 710

### ISSUE THREAD

**Issue by TheVietboi** [ChalkyBrush/roshpit-bug-tracker#1588] opened 2020-07-13 06:47 UTC
STEP TO REPRODUCE:
1.) Equip a pair of Redfall Runners
2.) Invest some Spirit and Agility so that the boots gives you >710 movespeed
3.) Use E
4.) Observe that your movespeed is reduced instead

**Comment by redledcat** [comment] 2020-07-15 11:18
Yeah sorry it's my shitty code
also duplicate of #1447

**Comment by redledcat** [comment] 2020-07-15 12:13
I'm trying my best to fix it right now lol

**Comment by redledcat** [comment] 2020-10-01 10:33
mind checking it if it's fixed, because it was patched on 19 July

**Comment by redledcat** [comment] 2020-10-04 08:01
yep it's fine now

**Comment by redledcat** [comment] 2020-10-04 08:01
![image](https://user-images.githubusercontent.com/32621322/95010325-00b5a300-0631-11eb-8f48-8a75a2586097.png)

**Closed as completed by redledcat** 2020-10-04 08:01 UTC
