### ISSUE TITLE
[Arkinus] W3 not working during Archon form

### ISSUE THREAD

**Issue by ngcongninh** [ChalkyBrush/roshpit-bug-tracker#1156] opened 2019-04-30 17:49 UTC
W3 Photon Sprint not work during Archon Form(R skill when have arcana Archon Armor)

**Comment by DeckardCainRPC** [comment] 2019-04-30 20:05
please ensure that W is toggled on when you right-click an enemy unit. if W is not toggled on at that time, then W3 will not activate.

additionally, i will note that Archon Form gives Arkimus a long attack range, and that W3's effect will be removed as soon as Arkimus launches an autoattack. in order to utilize W3 with Archon Form, you will have to repeatedly spam right-click on targets to continuously re-activate W3.

**Comment by redledcat** [comment] 2019-04-30 22:45
Not enough info / not a bug
checked it in game, W3 works. closing

**Closed as completed by redledcat** 2019-04-30 22:45 UTC
